### PR TITLE
Ensure ImageView.drawable is not null before attempting to darken it.

### LINKED ISSUE #691: Crash reported in DarkenImage trasition
```
Fatal Exception: java.lang.IllegalStateException
iv.drawable must not be null
io.plaidapp.core.ui.transitions.DarkenImage$createAnimator$$inlined$apply$lambda$1.onAnimationUpdate (DarkenImage.kt:67)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1522)
android.animation.ValueAnimator.setCurrentFraction (ValueAnimator.java:654)
android.animation.ValueAnimator.setCurrentPlayTime (ValueAnimator.java:617)
android.animation.ValueAnimator.start (ValueAnimator.java:1046)
android.animation.ValueAnimator.start (ValueAnimator.java:1065)
android.transition.Transition.animate (Transition.java:1881)
android.transition.Transition.runAnimator (Transition.java:901)
android.transition.Transition.runAnimators (Transition.java:879)
android.transition.TransitionSet.runAnimators (TransitionSet.java:433)
android.transition.TransitionSet.runAnimators (TransitionSet.java:433)
android.transition.TransitionSet.runAnimators (TransitionSet.java:433)
android.transition.TransitionSet.runAnimators (TransitionSet.java:433)
android.transition.Transition.playTransition (Transition.java:1780)
android.transition.TransitionManager$MultiListener.onPreDraw (TransitionManager.java:315)
android.view.ViewTreeObserver.dispatchOnPreDraw (ViewTreeObserver.java:977)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2374)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1416)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6845)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:966)
android.view.Choreographer.doCallbacks (Choreographer.java:778)
android.view.Choreographer.doFrame (Choreographer.java:713)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:952)
android.os.Handler.handleCallback (Handler.java:789)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6798)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
```

### PR DESCRIPTION
**Pull request by nickbutcher**
## :loudspeaker: Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring

## :scroll: Description

Check if the `drawable` in an `ImageView` is `null` before creating an `Animator` over it in the `DarkenImage` transition.

## :bulb: Motivation and Context

Fixes #691

## :green_heart: How did you test it?
Manually on device.

## :pencil: Checklist

- [x] I ran `./gradlew spotlessApply` before submitting the PR
- [x] I reviewed submitted code
- [ ] I added tests to verify changes
- [x] All tests passing

### CODE REVIEW

File: core/src/main/java/io/plaidapp/core/ui/transitions/DarkenImage.kt [hunk 1]
```diff
@@ -59,6 +59,7 @@ class DarkenImage(context: Context, attrs: AttributeSet) : Transition(context, a
         if (!isDarkTheme) return null
         if (initialRgbScale == finalRgbScale) return null
         val iv = endValues?.view as? ImageView ?: return null
+        if (iv.drawable == null) return null
```
Comment (piotrek1543) [inline core/src/main/java/io/plaidapp/core/ui/transitions/DarkenImage.kt]: Hi, what about
` val drawable = (iv.drawable) ?: return null`
and then
`drawable.colorFilter = ColorMatrixColorFilter(cm)`
instead of 
`iv.drawable.colorFilter = ColorMatrixColorFilter(cm)`
Small change, but removes duplicated `iv.drawable` variable :-)

Comment (nickbutcher) [reply core/src/main/java/io/plaidapp/core/ui/transitions/DarkenImage.kt]: nice, thanks for the suggestion 🙌
